export { CommentInput } from './CommentInput';
export type { CommentInputProps } from './CommentInput';
export { TemplateSaveSection } from './TemplateSection';
export { DocumentInfoSection } from './DocumentInfoSection';
export { TagsSection } from './TagsSection';
export { SummarySection } from './SummarySection';
export { SourceLinksSection } from './SourceLinksSection';
export { AttachmentsSection } from './ActivitySections';
export { CommentsSection } from './CommentsSection';
export type { CommentsSectionProps } from './CommentsSection';
