/**
 * @ssoo/types - 공유 타입 패키지
 *
 * 사용법:
 * - import { ApiResponse, User } from '@ssoo/types/common';
 * - import { Project, Customer } from '@ssoo/types/pms';
 *
 * 하위 호환성을 위해 루트에서도 모든 타입을 re-export합니다.
 */

// Common Types
export type {
  AccessInspectionObjectSnapshot,
  AccessInspectionResult,
  AccessInspectionSnapshot,
  AccessInspectionSubject,
  ApiResponse,
  PaginationParams,
  IdParam,
  PermissionExceptionAxis,
  PermissionExceptionListResult,
  PermissionExceptionRecord,
  PermissionEffectType,
  PermissionResolutionTrace,
  LoginRequest,
  AuthTokens,
  AuthIdentity,
  SsooAppKey,
  AuthSessionStatus,
  AuthSessionBootstrap,
  AuthLogoutResult,
  AuthUser,
  UserRole,
  User,
  CreateUserDto,
  UpdateUserDto,
} from './common';

// PMS Types
export type {
  ProjectStatusCode,
  ProjectStageCode,
  ProjectPhase,
  ProjectLifecycleStatus,
  DoneResultCode,
  ProjectLifecycle,
  Project,
  CreateProjectDto,
  UpdateProjectDto,
  ProjectRequestDetail,
  ProjectProposalDetail,
  ProjectExecutionDetail,
  ProjectTransitionDetail,
  ProjectHandoffTypeCode,
  ProjectHandoffStatusCode,
  ProjectHandoff,
  CreateProjectHandoffDto,
  UpdateProjectHandoffDto,
  ProjectContractTypeCode,
  ProjectContractStatusCode,
  ProjectContract,
  CreateProjectContractDto,
  UpdateProjectContractDto,
  ContractPaymentTypeCode,
   ContractPaymentStatusCode,
   ContractPayment,
   CreateContractPaymentDto,
   UpdateContractPaymentDto,
   ProjectOrgRoleCode,
    ProjectOrg,
    CreateProjectOrgDto,
    UpdateProjectOrgDto,
    ProjectRelationTypeCode,
    ProjectRelation,
    CreateProjectRelationDto,
    ProjectStatus,
    ProjectDetail,
   UpsertRequestDetailDto,
  UpsertProposalDetailDto,
  UpsertExecutionDetailDto,
   UpsertTransitionDetailDto,
   AdvanceStageDto,
   TransitionResult,
   PmsProjectAccessFeatures,
   PmsProjectAccessRoles,
   PmsProjectAccessSnapshot,
   Customer,
   CreateCustomerDto,
   UpdateCustomerDto,
  Task,
  CreateTaskDto,
  UpdateTaskDto,
  Milestone,
  CreateMilestoneDto,
  UpdateMilestoneDto,
  ProjectMember,
  ProjectMemberAccessLevel,
  CreateProjectMemberDto,
  UpdateProjectMemberDto,
  Objective,
  CreateObjectiveDto,
  UpdateObjectiveDto,
   Wbs,
   CreateWbsDto,
   UpdateWbsDto,
   Issue,
    CreateIssueDto,
    UpdateIssueDto,
    ProjectIssueTypeCode,
    ProjectIssueStatusCode,
    ProjectIssue,
    CreateProjectIssueDto,
    UpdateProjectIssueDto,
    ProjectRequirementStatusCode,
    ProjectRequirement,
    CreateProjectRequirementDto,
   UpdateProjectRequirementDto,
   ProjectRiskStatusCode,
   ProjectRisk,
   CreateProjectRiskDto,
   UpdateProjectRiskDto,
   ProjectChangeRequestStatusCode,
   ProjectChangeRequest,
   CreateProjectChangeRequestDto,
   UpdateProjectChangeRequestDto,
    ProjectEventTypeCode,
    ProjectEventStatusCode,
    ProjectEvent,
    ProjectEventRollup,
    ProjectEventWithRollup,
    CreateProjectEventDto,
    UpdateProjectEventDto,
    PmsAccessType,
   PmsAccessMenuItem,
   PmsFavoriteMenuItem,
   PmsAccessSnapshot,
} from './pms';

// CMS (Content Management System)
export type { CmsVisibilityScopeCode, Post, CreatePostDto, UpdatePostDto } from './cms/post';
export type { Comment, CreateCommentDto, UpdateCommentDto } from './cms/comment';
export type { Board, BoardCategory, CreateBoardDto, UpdateBoardDto } from './cms/board';
export type { UserProfile, UserCareer, UpdateProfileDto, CreateCareerDto } from './cms/profile';
export type { Skill, UserSkill, Endorsement, CreateSkillDto, AddUserSkillDto, EndorseSkillDto, SearchExpertsDto } from './cms/skill';
export type { Follow, FollowStats } from './cms/follow';
export type { NotificationType, Notification } from './cms/notification';
export type { FeedItem, FeedQueryDto, ReactionDto } from './cms/feed';
export type { CmsFeatureAccess, CmsAccessSnapshot } from './cms/access';

// DMS (Document Management System)
export type {
  FileNode,
  DocumentAcl,
  DocumentMutationAction,
  DocumentIsolationReasonCode,
  DocumentIsolationState,
  SourceFileMeta,
  DocumentComment,
  BodyLink,
  DocumentMetadata,
  ExtractedImageItem,
  ReferenceFileOrigin,
  ReferenceFile,
  TemplateScope,
  TemplateKind,
  TemplateVisibility,
  TemplateStatus,
  TemplateSourceType,
  TemplateOriginType,
  TemplateReferenceDoc,
  TemplateGeneration,
  ScrapeEntry,
  UserTemplateManifest,
  TemplateItem,
  ContentType,
  ContentMetadataBase,
  DocumentContentMetadata,
  TemplateContentMetadata,
  ContentMetadata,
  SearchContextMode,
  SearchConfidence,
  SearchCitation,
  SearchResultItem,
  SearchResponse,
  AiContextOptions,
  SearchRequest,
  SearchIndexSyncAction,
  SearchIndexSyncRequest,
  SearchIndexSyncResponse,
  AskContextMode,
  AskMessagePart,
  AskMessageInput,
  AskTemplateInput,
  AskRequest,
  AskResponse,
  CreateSummaryTemplateType,
  CreateSummaryRequest,
  DmsFeatureAccess,
  DmsAccessSnapshot,
  DmsDocumentAccessRequestRole,
  DmsDocumentAccessRequestStatus,
  DmsDocumentAccessRequestStatusFilter,
  DmsDocumentAccessRequestActor,
  DmsDocumentAccessRequestState,
  DmsDocumentAccessRequestSummary,
  CreateDmsDocumentAccessRequestPayload,
  DmsDocumentAccessRequestListQuery,
  ApproveDmsDocumentAccessRequestPayload,
  RejectDmsDocumentAccessRequestPayload,
} from './dms';
