/**
 * @ssoo/types - 공유 타입 패키지
 *
 * 사용법:
 * - import { ApiResponse, User } from '@ssoo/types/common';
 * - import { Project, Customer } from '@ssoo/types/pms';
 *
 * 하위 호환성을 위해 루트에서도 모든 타입을 re-export합니다.
 */

// Common Types
export type {
  AccessInspectionObjectSnapshot,
  AccessInspectionResult,
  AccessInspectionSnapshot,
  AccessInspectionSubject,
  ApiResponse,
  PaginationParams,
  IdParam,
  PermissionExceptionAxis,
  PermissionExceptionListResult,
   PermissionExceptionRecord,
   PermissionEffectType,
   PermissionResolutionTrace,
   CommonNotificationAction,
   CommonNotificationActionType,
   CommonNotificationItem,
    CommonNotificationJsonValue,
    CommonNotificationArchiveResult,
    CommonNotificationListQuery,
   CommonNotificationListResult,
   CommonNotificationMarkAllReadResult,
    CommonNotificationReference,
    CommonNotificationSeverity,
    CommonNotificationSourceApp,
    CommonNotificationStreamEvent,
    CommonNotificationStreamEventType,
    CommonNotificationUnreadCountResult,
    CommonSearchBadge,
    CommonSearchBlockedSourceReason,
    CommonSearchBlockedSourceSummary,
    CommonSearchCapabilities,
    CommonSearchEntityFacet,
    CommonSearchEntityType,
    CommonSearchFacets,
    CommonSearchPermissionState,
    CommonSearchRanker,
    CommonSearchRequest,
    CommonSearchResponse,
    CommonSearchResult,
    CommonSearchSourceApp,
    CommonSearchSourceFacet,
    CommonSearchTarget,
    LoginRequest,
  AuthTokens,
  AuthIdentity,
  ProfileSummary,
  AuthProfileDisplayProjection,
  AuthIdentityProfileProjection,
  SsooAppKey,
  AuthSessionStatus,
  AuthSessionBootstrap,
  AuthLogoutResult,
  AuthUser,
  AuthIdentityProviderKey,
  AuthRegistrationRequestStatus,
  AuthEmailDeliveryMode,
  AuthPublicActionLink,
  AuthPublicIdentityProvider,
  AuthPublicLoginConfig,
  AuthProviderSettings,
  UpdateAuthProviderSettingsRequest,
  AuthRegistrationRequestItem,
  AuthRegistrationRequestListResult,
  AuthAssignableRole,
  DecideAuthRegistrationRequest,
  RequestPasswordResetRequest,
  RequestPasswordResetResult,
  ConfirmPasswordResetRequest,
  ConfirmPasswordResetResult,
  UserRole,
  User,
  CreateUserDto,
  UpdateUserDto,
} from './common';

export type {
  AiAclPolicyCode,
  AiChunkSnapshot,
  AiConversationCreateRequest,
  AiConversationScopeCode,
  AiConversationSnapshot,
  AiConversationStatusCode,
  AiConversationUpdateRequest,
  AiIndexJobStatusCode,
  AiIndexJobTypeCode,
  AiIndexProjection,
  AiJsonValue,
  AiMessageAppendRequest,
  AiMessageRoleCode,
  AiMessageSnapshot,
  AiMessageStatusCode,
  AiObjectKey,
  AiObjectSensitivityCode,
  AiReferenceInput,
  AiReferenceKindCode,
  AiReferenceSnapshot,
  AiRetrievalCitation,
  AiRetrievalModeCode,
  AiRetrievalRequest,
  AiRetrievalResponse,
  AiRetrievalStatusCode,
  AiRunCompleteRequest,
  AiRunSnapshot,
  AiRunSourceInput,
  AiRunSourceKindCode,
  AiRunSourceSnapshot,
  AiRunStartRequest,
  AiRunStatusCode,
  AiRunTypeCode,
  AiSourceStatusCode,
} from './common/ai';

export type {
  AiIndexAccessScopeCode,
  AiIndexAclProjection,
  AiIndexAdapterSyncRequest,
  AiIndexAdapterSyncResult,
  AiIndexApplyResult,
  AiIndexChunkProjection,
  AiIndexEmbeddingSyncSnapshot,
  AiIndexEmbeddingProfile,
  AiIndexEntityType,
  AiIndexJobErrorKind,
  AiIndexJobRequest,
  AiIndexJobRunResult,
  AiIndexJobRunSummary,
  AiIndexJobSafetyInput,
  AiIndexJobSafetySnapshot,
  AiIndexJobSnapshot,
  AiIndexJobStatus,
  AiIndexJobType,
  AiIndexJsonObject,
  AiIndexJsonValue,
  AiIndexObjectProjection,
  AiIndexObjectRef,
  AiIndexObjectStatus,
  AiIndexSensitivityCode,
  AiIndexSourceApp,
  AiIndexSourceStatus,
} from './common/ai-index';

export type {
  AiRetrievalCitation as CommonAiRetrievalCitation,
  AiRetrievalContextItem,
  AiRetrievalRequest as CommonAiRetrievalRequest,
  AiRetrievalResponse as CommonAiRetrievalResponse,
  AiRetrievalResultItem,
} from './common/ai-retrieval';

// PMS Types
export type {
  ProjectStatusCode,
  ProjectStageCode,
  ProjectPhase,
  ProjectLifecycleStatus,
  DoneResultCode,
  ProjectLifecycle,
  Project,
  CreateProjectDto,
  UpdateProjectDto,
  ProjectRequestDetail,
  ProjectProposalDetail,
  ProjectExecutionDetail,
  ProjectTransitionDetail,
  ProjectHandoffTypeCode,
  ProjectHandoffStatusCode,
  ProjectHandoff,
  CreateProjectHandoffDto,
  UpdateProjectHandoffDto,
  ProjectContractTypeCode,
  ProjectContractStatusCode,
  ProjectContract,
  CreateProjectContractDto,
  UpdateProjectContractDto,
  ContractPaymentTypeCode,
   ContractPaymentStatusCode,
   ContractPayment,
   CreateContractPaymentDto,
   UpdateContractPaymentDto,
   ProjectOrgRoleCode,
    ProjectOrg,
    CreateProjectOrgDto,
    UpdateProjectOrgDto,
    ProjectRelationTypeCode,
    ProjectRelation,
    CreateProjectRelationDto,
    ProjectStatus,
    ProjectDetail,
   UpsertRequestDetailDto,
  UpsertProposalDetailDto,
  UpsertExecutionDetailDto,
   UpsertTransitionDetailDto,
   AdvanceStageDto,
   TransitionResult,
   PmsProjectAccessFeatures,
   PmsProjectAccessRoles,
   PmsProjectAccessSnapshot,
   PmsHomeRelation,
   PmsHomeCapabilityKey,
   PmsHomeActionKind,
   PmsHomeTargetTab,
   PmsHomeAllowedAction,
   PmsHomeSignalKind,
   PmsHomeSignalSeverity,
   PmsHomeSignal,
   PmsHomeRelationCounts,
   PmsHomeMetrics,
   PmsHomeFlowItem,
   PmsHomeRecentChange,
   PmsHomeAccessProject,
   PmsHomeSummary,
   Customer,
   CreateCustomerDto,
   UpdateCustomerDto,
  Task,
  CreateTaskDto,
  UpdateTaskDto,
  Milestone,
  CreateMilestoneDto,
  UpdateMilestoneDto,
  ProjectMember,
  ProjectMemberAccessLevel,
  CreateProjectMemberDto,
  UpdateProjectMemberDto,
  Objective,
  CreateObjectiveDto,
  UpdateObjectiveDto,
   Wbs,
   CreateWbsDto,
   UpdateWbsDto,
   Issue,
    CreateIssueDto,
    UpdateIssueDto,
    ProjectIssueTypeCode,
    ProjectIssueStatusCode,
    ProjectIssue,
    CreateProjectIssueDto,
    UpdateProjectIssueDto,
    ProjectRequirementStatusCode,
    ProjectRequirement,
    CreateProjectRequirementDto,
   UpdateProjectRequirementDto,
   ProjectRiskStatusCode,
   ProjectRisk,
   CreateProjectRiskDto,
   UpdateProjectRiskDto,
   ProjectChangeRequestStatusCode,
   ProjectChangeRequest,
   CreateProjectChangeRequestDto,
   UpdateProjectChangeRequestDto,
    ProjectEventTypeCode,
    ProjectEventStatusCode,
    ProjectEvent,
    ProjectEventRollup,
    ProjectEventWithRollup,
    CreateProjectEventDto,
    UpdateProjectEventDto,
    PmsAccessType,
   PmsAccessMenuItem,
   PmsFavoriteMenuItem,
   PmsAccessSnapshot,
} from './pms';

// SNS
export type { SnsVisibilityScopeCode, Post, CreatePostDto, UpdatePostDto } from './sns/post';
export type { Comment, CreateCommentDto, UpdateCommentDto } from './sns/comment';
export type { Board, BoardCategory, CreateBoardDto, UpdateBoardDto } from './sns/board';
export type {
  ProfileSkill,
  ProfileUserSummary,
  UserProfile,
  UserProfileSurface,
  UserCareer,
  UpdateProfileDto,
  CreateCareerDto,
} from './sns/profile';
export type { Skill, UserSkill, Endorsement, CreateSkillDto, AddUserSkillDto, EndorseSkillDto, SearchExpertsDto } from './sns/skill';
export type { Follow, FollowStats } from './sns/follow';
export type { NotificationType, Notification } from './sns/notification';
export type { FeedItem, FeedQueryDto, ReactionDto } from './sns/feed';
export type { SnsFeatureAccess, SnsAccessSnapshot } from './sns/access';

// DMS (Document Management System)
export type {
  FileNode,
  DocumentAcl,
  DocumentMutationAction,
  DocumentIsolationReasonCode,
  DocumentIsolationState,
  SourceFileMeta,
  DocumentComment,
  BodyLink,
  DocumentMetadata,
  ExtractedImageItem,
  ReferenceFileOrigin,
  ReferenceFile,
  TemplateScope,
  TemplateKind,
  TemplateVisibility,
  TemplateStatus,
  TemplateSourceType,
  TemplateOriginType,
  TemplateReferenceDoc,
  TemplateGeneration,
  ScrapeEntry,
  UserTemplateManifest,
  TemplateItem,
  ContentType,
  ContentMetadataBase,
  DocumentContentMetadata,
  TemplateContentMetadata,
  ContentMetadata,
  SearchContextMode,
  SearchConfidence,
  SearchCitation,
  SearchBlockedSourceReasonCode,
  SearchBlockedSourceReason,
  SearchBlockedSourceSummary,
  SearchResultItem,
  SearchResponse,
  AiContextOptions,
  SearchRequest,
  SearchIndexSyncAction,
  SearchIndexSyncRequest,
  SearchIndexSyncResponse,
  AskContextMode,
  AskMessagePart,
  AskMessageInput,
  AskTemplateInput,
  AskRequest,
  AskResponse,
  CreateSummaryTemplateType,
  CreateSummaryRequest,
  DmsFeatureAccess,
  DmsAccessSnapshot,
  DmsDocumentAccessRequestRole,
  DmsDocumentAccessRequestStatus,
  DmsDocumentAccessRequestStatusFilter,
  DmsDocumentAccessRequestActor,
  DmsDocumentAccessRequestState,
  DmsDocumentAccessRequestSummary,
  CreateDmsDocumentAccessRequestPayload,
  DmsDocumentAccessRequestListQuery,
  ApproveDmsDocumentAccessRequestPayload,
  RejectDmsDocumentAccessRequestPayload,
  UpdateDocumentVisibilityPayload,
  TransferDocumentOwnershipPayload,
  TransferDocumentOwnershipResult,
  CreateDmsDocumentDirectGrantPayload,
  DmsDocumentDirectGrantResult,
  CreateDmsDocumentCommentPayload,
  DmsDocumentCommentMutationResult,
  DmsDocumentCommentsResult,
  MutateDmsDocumentCommentPayload,
} from './dms';
export type {
  CrmAdminBoundary,
  CrmIntegrationStatus,
  CrmOpportunity,
  CrmOpportunityLine,
  CrmOpportunityListQuery,
  CrmOpportunityListResponse,
  CrmOpportunityPriority,
  CrmOpportunitySort,
  CrmOpportunityStatus,
  CrmOpportunitySummary,
} from './crm/index.js';
