import type { CrmDashboardResponse } from '@ssoo/types/crm';

export const crmDashboardFallback: CrmDashboardResponse = {
  generatedAt: '',
  boundaryNotice: '계약/청구/매출/원가는 CRM 원장, PMS 수행과 DMS 문서 lifecycle은 경계로 분리합니다. DMS markdown 초안 저장은 계약 상세에서만 제한적으로 수행합니다.',
  sellerInfoStatus: 'not-configured',
  opportunitySummary: {
    totalCount: 0,
    filteredCount: 0,
    qualifiedCount: 0,
    proposalCount: 0,
    wonCount: 0,
    totalRevenue: 0,
    totalCost: 0,
    totalMargin: 0,
    grossMarginRate: 0,
    boundaryNotice: '계약/청구/매출/원가는 CRM, 실행 수행은 PMS, 계정/권한/법인/조직은 공용 Admin 경계로 분리합니다.',
    unimplementedIntegrations: ['견적 생성', '계약 전환', 'DMS 연결', 'PMS 인계'],
    activeFilters: { search: '', status: 'all', sort: 'updated-desc' },
  },
  contractSummary: {
    totalCount: 0,
    filteredCount: 0,
    reviewCount: 0,
    activeCount: 0,
    completedCount: 0,
    totalRevenue: 0,
    totalCost: 0,
    totalExternalCost: 0,
    totalMargin: 0,
    grossMarginRate: 0,
    boundaryNotice: 'CRM은 계약/청구 원장과 계약 금액 기준값을 소유하고 PMS/DMS는 읽기용 패킷만 소비합니다.',
    unimplementedIntegrations: ['DMS 계약서 저장', 'PMS 프로젝트 생성'],
    activeFilters: { search: '', status: 'all', sort: 'updated-desc' },
  },
  pipeline: [
    { status: 'draft', label: '초안', count: 0, revenueTotal: 0, marginTotal: 0 },
    { status: 'qualified', label: '검증', count: 0, revenueTotal: 0, marginTotal: 0 },
    { status: 'proposal', label: '제안', count: 0, revenueTotal: 0, marginTotal: 0 },
    { status: 'won', label: '수주', count: 0, revenueTotal: 0, marginTotal: 0 },
    { status: 'lost', label: '실주', count: 0, revenueTotal: 0, marginTotal: 0 },
    { status: 'hold', label: '보류', count: 0, revenueTotal: 0, marginTotal: 0 },
  ],
  queues: [
    { key: 'quote', label: '견적 후보', count: 0, readyCount: 0, blockedCount: 0, amountTotal: 0, href: '/', state: 'blocked', description: '영업기회 원장 기반 읽기 전용 견적 후보' },
    { key: 'contract-conversion', label: '계약 전환', count: 0, readyCount: 0, blockedCount: 0, amountTotal: 0, href: '/', state: 'blocked', description: '최신 확정 영업기회 중 계약 원장 전환 대기' },
    { key: 'pms-handoff', label: 'PMS 인계', count: 0, readyCount: 0, blockedCount: 0, amountTotal: 0, href: '/contracts', state: 'blocked', description: '확정 계약의 실행 스냅샷 readiness' },
    { key: 'dms-document', label: 'DMS 문서 패킷', count: 0, readyCount: 0, blockedCount: 0, amountTotal: 0, href: '/contracts', state: 'blocked', description: '계약서 생성 전 입력 변수와 공급자 정보 readiness' },
  ],
  nextActions: [],
  sourceCompatibility: {
    calculationBasis: 'latest-confirmed-version-raw-total',
    calculationNotice: '각 영업기회의 확정된 차수 중 최신 차수를 집계합니다. 원천 대시보드와 동일하게 DC·절사 전 수량×단가 합계를 사용합니다.',
    confirmedSummary: {
      totalGroupCount: 0,
      confirmedLatestCount: 0,
      revenueTotal: 0,
      costTotal: 0,
      marginTotal: 0,
      marginRate: 0,
    },
    statusDistribution: [
      { status: '진행중', count: 0, percentage: 0 },
      { status: '검토중', count: 0, percentage: 0 },
      { status: '계약완료', count: 0, percentage: 0 },
      { status: '실패', count: 0, percentage: 0 },
    ],
    recentOpportunities: [],
  },
  unimplementedIntegrations: ['견적 생성', 'DMS 계약서 저장', 'PMS 프로젝트 생성'],
};
