export type {
  CrmDmsDocumentTemplateOption,
  CrmDmsDocumentTemplateTaskKey,
} from './document-template.js';

export type {
  CrmOpportunityContractDocumentArtifact,
  CrmOpportunityContractDocumentDraftRequest,
  CrmOpportunityContractDocumentDraftResult,
  CrmOpportunityContractDocumentHandoffSummary,
  CrmOpportunityContractDocumentLifecycleExecutionRequest,
  CrmOpportunityContractDocumentLifecycleExecutionResult,
  CrmOpportunityContractDocumentLifecycleStep,
  CrmOpportunityContractDocumentLifecycleStepKey,
  CrmOpportunityContractDocumentPreview,
  CrmOpportunityContractDocumentVariable,
  CrmOpportunityContractDocumentVariableKey,
  CrmOpportunityContractDocumentVariableSource,
} from './opportunity-contract-document.js';

export type {
  CrmCustomer,
  CrmCustomerActivity,
  CrmCustomerActivityCreateRequest,
  CrmCustomerAiIndexBackfillEntityType,
  CrmCustomerAiIndexBackfillItem,
  CrmCustomerAiIndexBackfillRequest,
  CrmCustomerAiIndexBackfillResponse,
  CrmCustomerActivityListQuery,
  CrmCustomerActivityListResponse,
  CrmCustomerActivityStatus,
  CrmCustomerActivityType,
  CrmCustomerListQuery,
  CrmCustomerListResponse,
  CrmCustomerListSummary,
  CrmCustomerRegion,
  CrmCustomerSort,
  CrmCustomerType,
  CrmCustomerUpsertRequest,
} from './customer.js';

export type {
  CrmBusinessPlanPreviewQuery,
  CrmBusinessPlanPreviewRegion,
  CrmBusinessPlanPreviewResponse,
  CrmBusinessPlanPreviewRow,
  CrmBusinessPlanPreviewSource,
  CrmBusinessPlanPreviewSummary,
  CrmBusinessPlanPreviewYear,
  CrmBusinessPlanPerformanceMonth,
  CrmBusinessPlanPerformanceMode,
  CrmBusinessPlanPerformanceActualInput,
  CrmBusinessPlanPerformanceActualInputRequest,
  CrmBusinessPlanPerformanceActualInputResult,
  CrmBusinessPlanPerformanceQuery,
  CrmBusinessPlanPerformanceResponse,
  CrmBusinessPlanPerformanceRow,
  CrmBusinessPlanPerformanceSource,
  CrmBusinessPlanPerformanceSummary,
  CrmBusinessPlan,
  CrmBusinessPlanCarryForwardRequest,
  CrmBusinessPlanDeleteResult,
  CrmBusinessPlanLine,
  CrmBusinessPlanListQuery,
  CrmBusinessPlanListResponse,
  CrmBusinessPlanListSummary,
  CrmBusinessPlanMonthlyPlanInputMode,
  CrmBusinessPlanMonthlyPlanInputRequest,
  CrmBusinessPlanMonthlyPlanInputResult,
  CrmBusinessPlanRow,
  CrmBusinessPlanRowMutationResult,
  CrmBusinessPlanRowUpsertRequest,
  CrmBusinessPlanRowWbsUpdateRequest,
  CrmBusinessPlanRowYear,
  CrmBusinessPlanSnapshotRequest,
  CrmBusinessPlanStatus,
} from './business-plan.js';

export type {
  CrmCostPlanAccountingPaymentHandoff,
  CrmCostPlanAccountingPaymentHandoffRequest,
  CrmCostPlanAccountingPaymentHandoffResult,
  CrmCostPlanAccountingPaymentHandoffStatus,
  CrmCostPlanAccountingPaymentHandoffSummary,
  CrmCostPlanAccountingPaymentExecutionArtifact,
  CrmCostPlanAccountingPaymentExecutionEvidenceRequest,
  CrmCostPlanAccountingPaymentExecutionEvidenceResult,
  CrmCostPlanAccountingPaymentExecutionEvidenceStep,
  CrmCostPlanAccountingPaymentExecutionMode,
  CrmCostPlanAccountingPaymentExecutionRequest,
  CrmCostPlanAccountingPaymentExecutionResult,
  CrmCostPlanAccountingPaymentExecutionStepKey,
  CrmCostPlanAccountingPaymentLine,
  CrmCostPlanAccountingPaymentLineSource,
  CrmCostPlanAccountingPaymentPreview,
  CrmCostPlanAccountingPaymentReadiness,
  CrmCostPlanAmsMappingStatus,
  CrmCostPlanAmsReadiness,
  CrmCostPlanAmsExternalInputStatus,
  CrmCostPlanAmsExternalMonthlyInput,
  CrmCostPlanAmsExternalMonthlyInputRequest,
  CrmCostPlanAmsExternalMonthlyInputResult,
  CrmCostPlanAmsExternalMonthlyWorkflowResult,
  CrmCostPlanAmsSourceEligibleWbs,
  CrmCostPlanAmsSourceExternalCostRequest,
  CrmCostPlanAmsSourceExternalCostRow,
  CrmCostPlanAmsSourceExternalCostRowInput,
  CrmCostPlanAmsSourceVendor,
  CrmCostPlanAmsSourceVendorCreateRequest,
  CrmCostPlanAmsSourceVendorWbs,
  CrmCostPlanAmsSourceVendorWbsRequest,
  CrmCostPlanAmsSourceWorkspace,
  CrmCostPlanAmsSourceWorkspaceResult,
  CrmCostPlanAmsVendorWbsMapping,
  CrmCostPlanAmsVendorWbsMappingRequest,
  CrmCostPlanAmsVendorWbsMappingResult,
  CrmCostPlanInternalInputMode,
  CrmCostPlanInternalInputStatus,
  CrmCostPlanInternalSourceGrid,
  CrmCostPlanInternalSourceGridRequest,
  CrmCostPlanInternalSourceGridResult,
  CrmCostPlanInternalSourceItem,
  CrmCostPlanInternalSourceItemCode,
  CrmCostPlanInternalSourceItemInput,
  CrmCostPlanInternalMonthlyInput,
  CrmCostPlanInternalMonthlyInputRequest,
  CrmCostPlanInternalMonthlyInputResult,
  CrmCostPlanInternalMonthlyWorkflowResult,
  CrmCostPlanPreviewMonth,
  CrmCostPlanPreviewQuery,
  CrmCostPlanPreviewRegion,
  CrmCostPlanPreviewResponse,
  CrmCostPlanPreviewRow,
  CrmCostPlanPreviewSource,
  CrmCostPlanPreviewSummary,
} from './cost-plan.js';

export type {
  CrmAccountingProviderMode,
  CrmDataQualityCheck,
  CrmDataQualityCheckKey,
  CrmDataQualityReport,
  CrmLaunchReadinessStatus,
  CrmLaunchReadinessSnapshot,
  CrmOperationAttempt,
  CrmOperationAttemptAction,
  CrmOperationAttemptListQuery,
  CrmOperationAttemptListResponse,
  CrmOperationRecoveryStatus,
  CrmOperationAttemptStatus,
  CrmOperationAttemptTarget,
  CrmOperationsAdminBoundaryItem,
  CrmOperationsBusinessYear,
  CrmOperationsCodeGroup,
  CrmOperationsCodeGroupKey,
  CrmOperationsCodeOption,
  CrmOperationsPreviewOwner,
  CrmOperationsPreviewQuery,
  CrmOperationsPreviewReadiness,
  CrmOperationsPreviewResponse,
  CrmOperationsPreviewSummary,
  CrmOperationsSellerProfileStatus,
  CrmReadiness,
  CrmReadinessCheck,
  CrmReadinessCheckKey,
  CrmSettings,
  CrmSettingsHistoryItem,
  CrmSettingsSource,
  CrmSettingsUpdateRequest,
} from './operations.js';

export type {
  CrmReportsAttentionItem,
  CrmReportsAttentionKind,
  CrmReportsBreakdown,
  CrmReportsBreakdownKind,
  CrmReportsConfirmation,
  CrmReportsConfirmationResult,
  CrmReportsConfirmationStatus,
  CrmReportsConfirmationSummary,
  CrmReportsConfirmRequest,
  CrmReportsMonthlyTrend,
  CrmReportsPreviewQuery,
  CrmReportsPreviewRegion,
  CrmReportsPreviewResponse,
  CrmReportsPreviewSummary,
} from './reports.js';

export type {
  CrmBillingSplitPreviewLine,
  CrmBillingSplitPreviewRequest,
  CrmBillingSplitPreviewResponse,
  CrmBillingSplitTarget,
  CrmContract,
  CrmContractBillingActualLine,
  CrmContractBillingActualResponse,
  CrmContractBillingActualSummary,
  CrmContractBillingActualUpsertLine,
  CrmContractBillingActualUpsertRequest,
  CrmContractBillingPlanLine,
  CrmContractBillingPlanUpsertLine,
  CrmContractDmsDocumentAttachment,
  CrmContractDmsDocumentAttachmentStatus,
  CrmContractDmsDocumentDraft,
  CrmContractDmsDocumentDraftRequest,
  CrmContractDmsDocumentExecutionEvidenceRequest,
  CrmContractDmsDocumentExecutionEvidenceResult,
  CrmContractDmsDocumentExecutionEvidenceStep,
  CrmContractDmsDocumentExecutionStepKey,
  CrmContractDmsDocumentLifecycleExecutionRequest,
  CrmContractDmsDocumentLifecycleExecutionArtifact,
  CrmContractDmsDocumentLifecycleExecutionResult,
  CrmContractDmsDocumentHandoff,
  CrmContractDmsDocumentHandoffStatus,
  CrmContractDmsDocumentHandoffSummary,
  CrmContractDmsDocumentLifecycleOwner,
  CrmContractDmsDocumentLifecycleStatus,
  CrmContractDmsDocumentLifecycleStep,
  CrmContractDmsDocumentLifecycleStepKey,
  CrmContractDmsDocumentPreview,
  CrmContractDmsDocumentReadiness,
  CrmContractDmsDocumentType,
  CrmContractDmsDocumentVariable,
  CrmContractDmsDocumentVariableSource,
  CrmContractLine,
  CrmContractListQuery,
  CrmContractListResponse,
  CrmContractPerformanceMonth,
  CrmContractPerformanceQuery,
  CrmContractPerformanceRegion,
  CrmContractPerformanceResponse,
  CrmContractPerformanceRow,
  CrmContractPerformanceSummary,
  CrmContractPmsHandoffFinancialSnapshot,
  CrmContractPmsHandoffPreview,
  CrmContractPmsHandoffReadiness,
  CrmContractSort,
  CrmContractStatus,
  CrmContractSummary,
  CrmContractUpsertLine,
  CrmContractUpsertRequest,
} from './contract.js';

export type {
  CrmDashboardNextAction,
  CrmDashboardNextActionKind,
  CrmDashboardPipelineStage,
  CrmDashboardQueue,
  CrmDashboardQueueKey,
  CrmDashboardQueueState,
  CrmDashboardResponse,
  CrmDashboardSourceCompatibility,
  CrmDashboardSourceConfirmedSummary,
  CrmDashboardSourceRecentOpportunity,
  CrmDashboardSourceStatusDistribution,
} from './dashboard.js';

export type {
  CrmDomainAccessFeatures,
  CrmDomainAccessSnapshot,
  CrmCustomerAccessFeatures,
  CrmCustomerAccessRoles,
  CrmCustomerAccessSnapshot,
  CrmCustomerGlobalAccessSnapshot,
  CrmOperationsAccessFeatures,
  CrmOperationsAccessSnapshot,
  CrmOpportunityAccessFeatures,
  CrmOpportunityAccessRoles,
  CrmOpportunityAccessSnapshot,
  CrmOpportunityGlobalAccessSnapshot,
} from './access.js';

export type {
  CrmAdminBoundary,
  CrmIntegrationStatus,
  CrmOpportunity,
  CrmOpportunityContractConversionRequest,
  CrmOpportunityContractConversionResponse,
  CrmOpportunityDeleteResult,
  CrmOpportunityDiscountType,
  CrmOpportunityHistoryEntry,
  CrmOpportunityHistoryEventType,
  CrmOpportunityHistoryListResponse,
  CrmOpportunityLine,
  CrmOpportunityLineCategory,
  CrmOpportunityListQuery,
  CrmOpportunityListResponse,
  CrmOpportunityOwnerLookupItem,
  CrmOpportunityOwnerLookupQuery,
  CrmOpportunityPriority,
  CrmOpportunityServiceType,
  CrmOpportunitySort,
  CrmOpportunityStatus,
  CrmSourceOpportunityStatus,
  CrmOpportunitySummary,
  CrmOpportunityUpsertLine,
  CrmOpportunityUpsertRequest,
  CrmOpportunityVersionListResponse,
  CrmOpportunityVersionSummary,
  CrmQuoteWorkflowStatus,
} from './opportunity.js';

export type {
  CrmQuoteDmsDocumentDraft,
  CrmQuoteDmsDocumentDraftRequest,
  CrmQuoteDmsDocumentExecutionEvidenceRequest,
  CrmQuoteDmsDocumentExecutionEvidenceResult,
  CrmQuoteDmsDocumentExecutionEvidenceStep,
  CrmQuoteDmsDocumentExecutionStepKey,
  CrmQuoteDmsDocumentHandoff,
  CrmQuoteDmsDocumentHandoffStatus,
  CrmQuoteDmsDocumentHandoffSummary,
  CrmQuoteDmsDocumentLifecycleExecutionRequest,
  CrmQuoteDmsDocumentLifecycleExecutionResult,
  CrmQuoteDmsDocumentLifecycleOwner,
  CrmQuoteDmsDocumentLifecycleStatus,
  CrmQuoteDmsDocumentLifecycleStep,
  CrmQuoteDmsDocumentLifecycleStepKey,
  CrmQuoteDmsDocumentPreview,
  CrmQuoteDmsDocumentReadiness,
  CrmQuoteDmsDocumentType,
  CrmQuoteDmsDocumentVariable,
  CrmQuoteDmsDocumentVariableSource,
  CrmQuoteDmsTemplateEvidence,
  CrmQuoteDmsTemplateEvidenceState,
  CrmQuoteDmsTemplateStatus,
  CrmOpportunityQuotePreview,
  CrmQuoteOwnerContactProfile,
  CrmQuoteSellerCiReferenceStatus,
  CrmQuoteSellerCiStatus,
  CrmQuoteSellerProfile,
  CrmQuoteSellerProfileUpsertRequest,
  CrmQuotePreviewOwnerContactStatus,
  CrmQuotePreviewLine,
  CrmQuotePreviewLineSection,
  CrmQuotePreviewParty,
  CrmQuotePreviewSellerInfoStatus,
  CrmQuotePreviewStatus,
  CrmQuotePreviewSummary,
  CrmQuotePreviewWorkflow,
  CrmQuoteWorkflowUpdateRequest,
} from './quote.js';

export type { CrmContractApprovalStatus, CrmContractApproval, CrmContractApprovalSource, CrmContractApprovalWorkspace, CrmContractApprovalCandidates, CrmContractApprovalInbox, CrmContractApprovalRequest, CrmContractApprovalDecision } from './contract-approval.js';
